### ISSUE TITLE
Cannot be evaluated with pretrained models

### ISSUE THREAD

**Issue by npduyduc** [svip-lab/PlaneDepth#1]
Hi I'm trying to run your eval.sh file with pretrained model and got this error can you help me, thanks

eval.sh
`CUDA_VISIBLE_DEVICES=0 python evaluate_depth_HR.py \
--eval_stereo \
--load_weights_folder pretrained/stage1 \
--models_to_load encoder depth \
--use_denseaspp \
--plane_residual \
--width 1280 \
--height 384`

error
`RuntimeError: Error(s) in loading state_dict for DepthDecoder:
        Missing key(s) in state_dict: "decoder.13.0.weight", "decoder.13.0.bias", "decoder.13.2.weight", "decoder.13.2.bias". 
        Unexpected key(s) in state_dict: "decoder.14.0.weight", "decoder.14.0.bias", "decoder.14.2.weight", "decoder.14.2.bias", "decoder.13.conv.weight", "decoder.13.conv.bias".`

**Comment by Dwawayu** [comment]
Im so sorry for forgetting to include the training flag --use_mixture_loss in the eval.sh😭, thank you for pointing out! You can add the flag --use_mixture_loss \ to eval.sh to fix it, additionally you may need to adjust the --batch_size to avoid OOM.
