### ISSUE TITLE
关于概率分布的疑问

### ISSUE THREAD

**Issue by Jamesgender** [svip-lab/PlaneDepth#11]
<img width="370" alt="image" src="https://github.com/svip-lab/PlaneDepth/assets/135774928/65b472b9-fd78-4b40-92b2-05d4defa04c8">
您好，感谢你们的工作，我看论文时有个问题。
Di是离散的视差值或者深度值，pi是离散的概率值。直觉上pi应该服从某种凸分布，为什么你们不直接使用拉普拉斯分布拟合pi而是使用了使用了很多拉普拉斯分布来混合获得这个值呢？
如果我的问题有根本性错误，请告诉我，谢谢

**Comment by sirenc** [comment]
您好，我也对这个概率分布有疑问，在阅读源码时发现实际计算pi用的就是πi / σi（包括计算[深度](https://github.com/svip-lab/PlaneDepth/blob/1e7e3b6cb4bf85495e5750dcc6df21a7f07fa14c/networks/depth_decoder.py#L282C26-L282C26)和[新视点图像](https://github.com/svip-lab/PlaneDepth/blob/main/trainer.py#L600)），与论文中的公式（4）和（7）并不一致，是我没有找到正确的代码位置吗？
希望您也能解答我的疑问，感谢！

**Comment by Dwawayu** [comment]
您好！感谢提问和关注！对于第一个问题，我们参考SMD-Nets，各个候选值都保留一个单独的分布建模概率。比如在前背景的交接处，我们期望在前景的候选值和背景的候选值上有双峰的拉普拉斯分布，而不是独立的凸分布。

对于第二个问题，πi / σi 是公式4，7的简化，误差很小，但效率更高。

**Comment by Jamesgender** [comment]
谢谢你们的解释。
