### ISSUE TITLE
can't find a suitable pretrained model

### ISSUE THREAD

**Issue by seemaywang** [svip-lab/PlaneDepth#13]
Thanks for your impressive work!
when I tested on custmo model,"load_state_dict(torch.load(os.path.join(opt.load_weights_folder, "plade.pth")))", but it seems like no pretrained model end with"plade.pth", could you please tell me which model is matched with PladeNet, thankyou!

**Comment by Dwawayu** [comment]
Hi! I apologize for the delayed response. The code segment you have referred to was part of our early experiments to test different network architectures and is now obsolete. You may need to update the [plade_net.py](https://github.com/svip-lab/PlaneDepth/blob/main/networks/plade_net.py) according to [depth_decoder.py](https://github.com/svip-lab/PlaneDepth/blob/main/networks/depth_decoder.py) and train a new ckpt with the flag `--net_type PladeNet`.

Please do not hesitate to contact me if you have any further issues.

**Comment by seemaywang** [comment]
Thanks a lot!!!
