### ISSUE TITLE
Possible licencing conflict

### ISSUE THREAD

**Issue by zshn25** [svip-lab/PlaneDepth#2]
Dear authors,

I appreciate your great work and I don't mean to be the party pooper but your codebase seems to be built upon [monodepth2](https://github.com/nianticlabs/monodepth2) which has a very restrictive [license](https://github.com/nianticlabs/monodepth2/blob/master/LICENSE). See `3.  Redistribution and modifications`. 

I don't think you can just use their code and re-license it to MIT License. 

I'm in no way related to Ninantic. Just a fellow researcher.

Best regards,
Zeeshan Khan Suri

**Comment by Dwawayu** [comment]
Dear Zeeshan,

Hi! I really appreciate your kind words and reminder. We have retained the copyright notice in the code from Monodepth2. But as you pointed out, we should also retain the unmodified Monodepth2 License. I deeply apologize for any confusion or inconvenience this oversight may have caused.

Upon your notice, I will promptly correct the license. Adhering to the proper open-source protocol is crucial for community, and I am grateful for your help.

Please do not hesitate to inform me if you come across any other issues.

Best regrads,
Ruoyu Wang

**Comment by Dwawayu** [comment]
Hi! It has been a while since the last comment, so I'm going to close this issue. You are welcome to reopen it or create a new one if there are any other issues. Thank you again for your reminder!
