### ISSUE TITLE
Unclear requirements.txt file 

### ISSUE THREAD

**Issue by BarRozenman** [svip-lab/PlaneDepth#3]
Hello I had a a hard time with the `requirements.txt` since there are some typos may I suggest this: 

pip install ipython==8.11.0
pip install matplotlib==3.5.0
pip install numpy==1.21.2
pip install opencv-python==4.5.5.62
pip install Pillow==9.4.0
pip install six==1.16.0
pip install tensorboardX==2.6
pip install scikit-image==0.18.3
torch==1.10.0
torchvision==0.11.1

**Comment by Dwawayu** [comment]
Hi, I'm sorry for providing the requirements file with so many typos and making you stuck in it. I have fixed them according to your suggestions, thank you!

If there are any other issues please let me know.
