### ISSUE TITLE
DataResize part code question

### ISSUE THREAD

**Issue by wangjiyuan9** [svip-lab/PlaneDepth#7]
Emm,
At [here](https://github.com/svip-lab/PlaneDepth/blob/main/datasets/pair_transforms.py) 41~48
I think `inputs[k],inputs[(n + "_aug", im)] and inputs[(n, im)]` are same???

**Comment by Dwawayu** [comment]
Hi! I want to remind that `Line 41-48` is for resizing cropping, while `Line 71-77` is for resizing only. You can use the `--no_crop` flag to choose which one to use.

Regarding your question of `Line 41-48`, `inputs[(n + "_aug", im)]` and `inputs[(n, im)]` are the same here, both cropped and resized. `inputs[k]` is only resized without cropping.

Later on, `inputs[(n + "_aug", im)]` will be further augmented in the color space, so all of them will be different.

By default, `inputs[(n + "_aug", im)]` is the input of network and `inputs[(n, im)]` is used for computing the loss. You can use `--match_aug` flag to compute loss on `inputs[(n + "_aug", im)]` if you wish.

I hope this answered your question. Please feel free to contact me if you meet any more questions.

**Comment by wangjiyuan9** [comment]
My previous understanding was superficial, thank you for your detailed explanation.

**Comment by wangjiyuan9** [comment]
Hi, I think I have a deep understanding of your code.
Actually ,your codes are robust to hold any condition.
But the `inputs[k]` really don't necessary. Because in the function `add_flip_right_inputs` you make the new inputs and never consider the `inputs[k]`.
So your code use another useless resize time to create `inputs[k]`. (the resize code will done over 100k time in training!)
