### ISSUE TITLE
GPU and efficiency

### ISSUE THREAD

**Issue by Sungmin-Woo** [svip-lab/PlaneDepth#9]
Hi @Dwawayu, thank you for sharing the code!
Could you please provide information on the GPU(s) used for this project and the quantity?
Additionally, it would be helpful to know the training and inference runtimes.

I'm looking forward to your reply!

**Comment by Dwawayu** [comment]
Hi! Thank you for your attention! Here is some information

**First stage:**
> Batch size: 8, 4 of which are flipped from the other 4.
> Epochs: 50
> Resolution: 640 * 192
> GPU memory: 20G
> Time: 3 days * 1 TITAN RTX, or 1 day * 4 2080Ti for me.

**HR finetuning:**
> Batch size: 8, 4 of which are flipped from the other 4.
> Epoch: 1
> Resolution: 1280 * 384
> GPU memory: 80G
>Time: 2.3 hours * 2 A40.

**Self-distillation:**
> Batch size: 4 without flipping
> Epochs: 10
> Resolution: 1280 * 384
> GPU memory: 43G
>Time: 14 hours * 2 A40, or 28 hours * 1 A40.

**Inference:**
> Resolution: 1280 * 384
> GPU: single 2080Ti
> Time: 45 ms per frame
> Time(pp): 82 ms per frame
> Time(sd): 101 ms per frame

I hope these help, please let me know if you have any other concerns.
